### ISSUE TITLE
UI doing a second refresh token after a previous one 

### ISSUE THREAD

**Issue by cesarhernandezgt** [tomitribe/microservice-with-jwt-and-microprofile#47]
When the UI gets a 401 from backend, the UI effectively trigger a POST to http://localhost:8080/oauth2/token with a `grant_type: refresh_token`.

Then the UI try again the original request using the newly obtained Access_token.

Then the UI triggers again a POST with a `grant_type: refresh_token`, This request is not necessary.

![image](https://user-images.githubusercontent.com/1454523/57798922-22944a00-770b-11e9-925f-42da7f0895cc.png)

**Comment by Dexmaster** [comment]
Should be fixed by PR https://github.com/tomitribe/microservice-with-jwt-and-microprofile/pull/50
