### ISSUE TITLE
UI log out the user when doing a refresh token flow

### ISSUE THREAD

**Issue by cesarhernandezgt** [tomitribe/microservice-with-jwt-and-microprofile#48]
when a session has an expired access token but a valid refresh token, the UI log out the user instead of doing first a Refresh Token process to then decide if the user obtains a new valid Access Token or if the used Refresh Token was also expired.

![Screen Shot 2019-05-15 at 12 18 59 PM](https://user-images.githubusercontent.com/1454523/57799325-1066db80-770c-11e9-94bb-2e91526cd0eb.png)
![Screen Shot 2019-05-15 at 12 18 23 PM](https://user-images.githubusercontent.com/1454523/57799326-1066db80-770c-11e9-9646-b1dcd33bcd32.png)

The above picture shows the scenario. The latest one shows when the user is logged out but notice that the Refresh token flow still occurs.

**Comment by cesarhernandezgt** [comment]
https://github.com/tomitribe/microservice-with-jwt-and-microprofile/pull/46 has a partial patch for this issue but it includes a Page Reload that covers a missing cleaning process of the UI refresh token flow.
![screencast 2019-05-15 12-26-13](https://user-images.githubusercontent.com/1454523/57799689-dba75400-770c-11e9-9449-93d4112ac9fe.gif)

**Comment by Dexmaster** [comment]
Should be fixed by https://github.com/tomitribe/microservice-with-jwt-and-microprofile/pull/50
